### ISSUE TITLE
the programme is in gibberish

### ISSUE THREAD

**Issue by Breadnanb** [HanleysFramer/CakeTools-AlphaPreview#1]
every time i open the programme it shows a bunch of random letters joint into one rather than actual words

**Comment by nothanley** [comment]
What region and language are you using? Are you on Windows 10?

**Comment by Breadnanb** [comment]
Yes, I use windows 10

**Comment by Breadnanb** [comment]
also, none of the buttons like the ones to add a new subfolder or extract and import don't work.

**Comment by nothanley** [comment]
The buttons are disabled until you open a .cak file or have clicked and opened a file from the "Files" table in the bottom left.

**Comment by nothanley** [comment]
Found the issue actually. Download and install these fonts: https://www.mediafire.com/file/47w9i53crt3egu1/CakeTools-UI-Fonts.zip/file. I forgot to package Lato-Regular with the exe, but i'll fix this by the next update.
